# CREDENTIALS AND VARIABLES TO RUN THE SCRIPT ON YOUR MACHINE

login = "YOUR_LOGIN" # LOGIN FROM SAP
password = "YOUR_PASSWORD" # PASSWORD
exportPath = r"YOUR_PATH_TO_EXPORT_.CSV_FILES" # FOLDER TO EXPORT AND READ .CSV FILES
sapExePath = r"YOUR_PATH_TO_SAP.EXE" # SAP .EXE LOCATION ON YOUR PC